# Generated by Django 4.1.3 on 2022-11-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_promotion_customer_gender_orderitem_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
